// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id: 1,
        title: "Unique products that will impress your home in 2023",
        author: "Admin",
        date: "August 17, 2024",
        tabs: "deco",
        bannerText: "Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…",
        quote: "Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.",
        sampleUrl: "/image/blocksDefault/block1/image2.jpg",
        imageUrl: "/image/blocksDefault/block1/image1.jpg",
        galleryUrl_1: "/image/blocksDefault/mainBlock/image1.jpg",
        galleryUrl_2: "/image/blocksDefault/mainBlock/image2.jpg",
    },
    {
        id: 2,
        title: "Navy Blue & White Striped Area Rugs",
        author: "Admin",
        date: "August 15, 2024",
        tabs: "deco",
        bannerText: "Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…",
        quote: "Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.",
        sampleUrl: "/image/blocksDefault/block2/image2.jpg",
        imageUrl: "/image/blocksDefault/block2/image1.jpg",
        galleryUrl_1: "/image/blocksDefault/mainBlock/image1.jpg",
        galleryUrl_2: "/image/blocksDefault/mainBlock/image2.jpg",
    },
    {
        id: 3,
        title: "Helendo White Coated Staircase Floating",
        author: "Admin",
        date: "August 8, 2024",
        tabs: "deco",
        bannerText: "Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…",
        quote: "Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.",
        sampleUrl: "/image/blocksDefault/block3/image2.jpg",
        imageUrl: "/image/blocksDefault/block3/image1.jpg",
        galleryUrl_1: "/image/blocksDefault/mainBlock/image1.jpg",
        galleryUrl_2: "/image/blocksDefault/mainBlock/image2.jpg",
    },
    {
        id: 4,
        title: "Spatialize with the decorations of the Helendo store.",
        author: "Admin",
        date: "August 6, 2024",
        tabs: "deco",
        bannerText: "Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…",
        quote: "Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.",
        sampleUrl: "/image/blocksDefault/block4/image2.jpg",
        imageUrl: "/image/blocksDefault/block4/image1.jpg",
        galleryUrl_1: "/image/blocksDefault/mainBlock/image1.jpg",
        galleryUrl_2: "/image/blocksDefault/mainBlock/image2.jpg",
    },
    {
        id: 5,
        title: "Decorate your home with the most modern furnishings.",
        author: "Admin",
        date: "August 1, 2024",
        tabs: "deco",
        bannerText: "Contrary to popular belief, Lorem Ipsum indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in…",
        quote: "Dalena dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etyt dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi utino aliquip ex ea commodo consequat.",
        sampleUrl: "/image/blocksDefault/block5/image2.jpg",
        imageUrl: "/image/blocksDefault/block5/image1.jpg",
        galleryUrl_1: "/image/blocksDefault/mainBlock/image1.jpg",
        galleryUrl_2: "/image/blocksDefault/mainBlock/image2.jpg",
    }
]